#import "../fragments/ListDraftsFragment.gql"

query ListDraftsQuery(
  $diaryID: ID!,
  $currentPage: Int!,
  $perPage: Int!,
  $order: ArticleOrder!
) {
  diary(id: $diaryID) {
    ...ListDraftsFragment
  }
}
