#import "../fragments/ListArticlesFragment.gql"

query ListArticlesQuery(
  $diaryID: ID!,
  $currentPage: Int!,
  $perPage: Int!,
  $order: ArticleOrder!,
  $states: [PublishState!]
) {
  diary(id: $diaryID) {
    ...ListArticlesFragment
  }
}
