// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

type Article struct {
	ID    string       `json:"id"`
	Title *string      `json:"title"`
	Body  *ArticleBody `json:"body"`
}

type ArticleBody struct {
	Markdown string `json:"markdown"`
	HTML     string `json:"html"`
}

type ArticleConnection struct {
	Nodes []*Article `json:"nodes"`
}

type Diary struct {
	Name     string             `json:"name"`
	Articles *ArticleConnection `json:"articles"`
}
