#import "../organisms/EditArticleInitialFragment.gql"

query GetArticleQuery($diaryID: ID!, $articleID: ID!) {
  diary(id: $diaryID) {
    article(id: $articleID) {
      ...EditArticleInitialFragment
    }
  }
}
