#import "../organisms/article.fragment.gql"
#import "../organisms/monodirectional-page-info.gql"

query ListArticles($diaryID: ID!, $articlesCount: Int!, $currentPage: Int!) {
  diary(id: $diaryID) {
    name
    publishedArticles(page: $currentPage, perPage: $articlesCount, orderBy: { direction: DESC, field: UPDATED_AT }) {
      nodes {
        ...ArticleFragment
      }
      pageInfo {
        ...MonodirectionalPageInfo
      }
    }
  }
}
