#import "./ListItemArticleFragment.gql"

fragment ListArticlesFragment on Diary {
  articles(page: $currentPage, perPage: $perPage, orderBy: $order) {
    pageInfo {
      hasNextPage
      nextPage
    }
    nodes {
      ...ListItemArticleFragment
    }
  }
}
