#import "./ListItemPublishedArticleFragment.gql"
#import "./ListItemDraftFragment.gql"

fragment ListArticlesFragment on Diary {
  articles(page: $currentPage, perPage: $perPage, orderBy: $order, states: $states) {
    pageInfo {
      hasNextPage
      nextPage
    }
    totalCount
    nodes {
      ...ListItemPublishedArticleFragment
      ...ListItemDraftFragment
    }
  }
}
