---

name: api

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1.1.2
        with:
          go-version: 1.12.13
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: dump deps
        run: go list -m -json all 
      - name: install
        run: go get -v all
      - name: test
        run: go test -cover -v ./...
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v1
      - name: setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@8958ac65db5da419b56f4ffbefc673774ba1434e
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          version: '272.0.0'
      - name: deploy
        run: |
          gcloud app deploy --quiet --project hibi-260613 --stop-previous-version ./api.app.yml
        env:
          CI: true
