---

name: app

on:
  pull_request:
  push:
    branches: [master]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      -
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: install
        run: yarn install --frozen-lockfile
  front-build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      -
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: install
        run: yarn install --frozen-lockfile
      - name: lint
        uses: reviewdog/action-eslint@v1.0.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          eslint_flags: '--ext .ts front/src/**/*'
      - name: build
        run: yarn workspace front build
  front-deploy:
    if: github.ref == 'refs/heads/master'
    needs: front-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup google cloud
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - run: |
          echo '{}' | jq --arg apiKey '${{ secrets.FIREBASE_API_KEY }}' --arg authDomain '${{ secrets.FIREBASE_AUTH_DOMAIN }}' --arg appId '${{ secrets.FIREBASE_APP_ID }}' '{FIREBASE_API_KEY: $apiKey, FIREBASE_AUTH_DOMAIN: $authDomain, FIREBASE_APP_ID: $appId}' > front/firebase-config.json
          cat front/firebase-config.json | jq --arg apiEndpoint 'https://api-dot-hibi-260613.appspot.com/graphql' '.API_ENDPOINT = $apiEndpoint' | tee front/firebase-config.json
      - name: deploy
        uses: actions/gcloud/cli@master
        with:
          args: app deploy --quiet --project hibi-260613 ./front.app.yml
        env:
          CI: true
  admin-build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      -
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: install
        run: yarn install --frozen-lockfile
      - name: lint
        uses: reviewdog/action-eslint@v1.0.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          eslint_flags: '--ext .ts admin/**/*'
      - name: test
        run: yarn workspace admin test
        env:
          CI: true
      - name: deploy
        run: yarn workspace admin deploy --token "${{ secrets.FIREBASE_TOKEN }}" --project "${{ secrets.GCLOUD_PROJECT }}"
        env:
          REACT_APP_API_ENDPOINT: https://api-dot-hibi-260613.appspot.com/graphql
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
